// Projects, the project graph and its nodes.
// Thin wrappers over the Axios client in client.js, grouped by area.
import web from './client.js'

export const createProject = (...args) => web.createProject(...args)
export const getProjects = (...args) => web.getProjects(...args)
export const updateProjectSizes = (...args) => web.updateProjectSizes(...args)
export const getStorageSummary = (...args) => web.getStorageSummary(...args)
export const getProject = (...args) => web.getProject(...args)
export const reindexProjectSearch = (...args) => web.reindexProjectSearch(...args)
export const deleteProject = (...args) => web.deleteProject(...args)
export const setProjectAttribute = (...args) => web.setProjectAttribute(...args)
export const getMyGraph = (...args) => web.getMyGraph(...args)
export const getGraph = (...args) => web.getGraph(...args)
export const rawQuery = (...args) => web.rawQuery(...args)
export const getSchemas = (...args) => web.getSchemas(...args)
export const getQueries = (...args) => web.getQueries(...args)
export const getGroups = (...args) => web.getGroups(...args)
export const getSchemaAndData = (...args) => web.getSchemaAndData(...args)
export const createNode = (...args) => web.createNode(...args)
export const deleteNode = (...args) => web.deleteNode(...args)
export const setNodeAttribute = (...args) => web.setNodeAttribute(...args)
export const setRelationAttribute = (...args) => web.setRelationAttribute(...args)
export const getNodePath = (...args) => web.getNodePath(...args)
export const getFileAncestors = (...args) => web.getFileAncestors(...args)
export const saveLayout = (...args) => web.saveLayout(...args)
export const getLayoutByTarget = (...args) => web.getLayoutByTarget(...args)
export const createSet = (...args) => web.createSet(...args)
export const createSource = (...args) => web.createSource(...args)
export const getSourceInit = (...args) => web.getSourceInit(...args)
export const getSetFiles = (...args) => web.getSetFiles(...args)
export const getStats = (...args) => web.getStats(...args)
export const getError = (...args) => web.getError(...args)
