// Services (crunchers), queues, processes, prompts and service help.
// Thin wrappers over the Axios client in client.js, grouped by area.
import web from './client.js'

export const getServices = (...args) => web.getServices(...args)
export const getQueueStatus = (...args) => web.getQueueStatus(...args)
export const getActiveJobs = (...args) => web.getActiveJobs(...args)
export const flushQueue = (...args) => web.flushQueue(...args)
export const cancelJob = (...args) => web.cancelJob(...args)
export const startService = (...args) => web.startService(...args)
export const stopService = (...args) => web.stopService(...args)
export const installService = (...args) => web.installService(...args)
export const forgetService = (...args) => web.forgetService(...args)
export const reloadServices = (...args) => web.reloadServices(...args)
export const getServicesForFile = (...args) => web.getServicesForFile(...args)
export const createFilter = (...args) => web.createFilter(...args)
export const getProcessParams = (...args) => web.getProcessParams(...args)
export const getQueue = (...args) => web.getQueue(...args)
export const getPrompts = (...args) => web.getPrompts(...args)
export const savePrompt = (...args) => web.savePrompt(...args)
export const getHelp = (...args) => web.getHelp(...args)
export const getServiceHelp = (...args) => web.getServiceHelp(...args)
export const getServiceHelpAsset = (...args) => web.getServiceHelpAsset(...args)
export const createFileProcess = (...args) => web.createFileProcess(...args)
export const createROIProcess = (...args) => web.createROIProcess(...args)
export const createSetProcess = (...args) => web.createSetProcess(...args)
export const createSourceProcess = (...args) => web.createSourceProcess(...args)
export const cancelProcess = (...args) => web.cancelProcess(...args)
export const getBatch = (...args) => web.getBatch(...args)
export const getBatchParams = (...args) => web.getBatchParams(...args)
export const pauseBatch = (...args) => web.pauseBatch(...args)
export const resumeBatch = (...args) => web.resumeBatch(...args)
export const cancelBatch = (...args) => web.cancelBatch(...args)
export const dismissJob = (...args) => web.dismissJob(...args)
